### ISSUE TITLE
Error when setting `denote-journal-extras-title-format` to nil 

### ISSUE THREAD

**Issue by tjstankus** [protesilaos/denote#176]
From the docs:

```
For example:

(setq denote-journal-extras-title-format 'day-date-month-year)

If the value of this user option is nil, then denote-journal-extras-new-entry will prompt for a title.
```

When setting `denote-journal-extras-title-format` to `nil`, I get `wrong type argument: stringp, nil` when running `denote-journal-extras-new-entry`.

**Comment by protesilaos** [comment]
Thank you @tjstankus! I just pushed the changes. Please let me know if it now works for you.

**Comment by tjstankus** [comment]
Thank you for addressing this so quickly @protesilaos! Unfortunately, I'm still hitting the same issue after updating. To provide more context, I'm using doom-emacs and the denote-specific part of my config looks like this:

```elisp
;; denote
(require 'denote)
(require 'denote-org-dblock)
(setq denote-directory (expand-file-name "~/Dropbox/org/denote"))
(require 'denote-journal-extras)
;; Set to nil to prompt for title
(setq denote-journal-extras-title-format nil)
```

In the meantime, there's a straightforward workaround:
- `(setq denote-journal-extras-title-format 'day-date-month-year)`
- edit file front matter
- `denote-rename-file-using-front-matter`

**Comment by protesilaos** [comment]
Oh, this is strange! Could it be that there was some old code kept around during your session and the new one will take effect upon restart? I can no longer reproduce the error: it works as expected on my end. 

Screenshots below.

## Ordinary prompt for title, with current date as the default value

![2023-10-16_16:29:46_1117x517](https://github.com/protesilaos/denote/assets/12828033/deb91f43-0772-4228-9a17-a2781a933510)

## User input at the prompt

![2023-10-16_16:29:55_1117x517](https://github.com/protesilaos/denote/assets/12828033/ad8644c5-6f90-48b5-8a85-14589475b28b)

## The resulting buffer

![2023-10-16_16:30:10_1117x517](https://github.com/protesilaos/denote/assets/12828033/9a364f43-1a61-46ed-8e39-eee112cfe4c6)

**Comment by tjstankus** [comment]
Thanks @protesilaos! I'm still seeing the issue. Again, not a big deal because I can work around it like I mentioned. And it may very well be something in my config. I recorded [this video](https://www.loom.com/share/924166464a6844a9bf51428043029322?sid=fe22eaaa-d85b-461a-a1a4-e994d33f82ee) showing the issue on my machine - maybe it will help. Thank you for your generous work on this package!

**Comment by protesilaos** [comment]
Thank you @tjstankus! I could not reproduce your issue, though I still rewrote the helper function. Here is its current implementation:

```elisp
(defun denote-journal-extras-daily--title-format ()
  "Return `denote-journal-extras-title-format' or prompt for title."
  (format-time-string
   (if (and denote-journal-extras-title-format
            (stringp denote-journal-extras-title-format))
       denote-journal-extras-title-format
     (pcase denote-journal-extras-title-format
       ('day "%A")
       ('day-date-month-year "%A %e %B %Y")
       ('day-date-month-year-24h "%A %e %B %Y %H:%M")
       ('day-date-month-year-12h "%A %e %B %Y %I:%M %^p")
       (_ (denote-title-prompt (format-time-string "%F")))))))
```

I also wrote this test for it:

```elisp
(ert-deftest denote-test--denote-journal-extras-daily--title-format ()
  "Make sure that `denote-journal-extras-daily--title-format' yields the desired format."
  (should (and
           ;; These three should prompt, but I am here treating the
           ;; prompt as if already returned a string.  The test for
           ;; the `denote-title-prompt' can be separate.
           (stringp
            (cl-letf (((symbol-function 'denote-title-prompt) #'identity)
                      (denote-journal-extras-title-format nil))
              (denote-journal-extras-daily--title-format)))

           (stringp
            (cl-letf (((symbol-function 'denote-title-prompt) #'identity)
                      (denote-journal-extras-title-format t))
              (denote-journal-extras-daily--title-format)))

           (stringp
            (cl-letf (((symbol-function 'denote-title-prompt) #'identity)
                      (denote-journal-extras-title-format :some-arbitrary-keyword))
              (denote-journal-extras-daily--title-format)))

           ;; And these return the following values
           (string-match-p
            "\\<.*?\\>"
            (let ((denote-journal-extras-title-format 'day))
              (denote-journal-extras-daily--title-format)))

           (string-match-p
            "\\<.*?\\> [0-9]\\{,2\\} \\<.*?\\> [0-9]\\{,4\\}"
            (let ((denote-journal-extras-title-format 'day-date-month-year))
              (denote-journal-extras-daily--title-format)))

           (string-match-p
            "\\<.*?\\> [0-9]\\{,2\\} \\<.*?\\> [0-9]\\{,4\\} [0-9]\\{,2\\}:[0-9]\\{,2\\} \\<.*?\\>"
            (let ((denote-journal-extras-title-format 'day-date-month-year-12h))
              (denote-journal-extras-daily--title-format)))

           (string-match-p
            "\\<.*?\\> [0-9]\\{,2\\} \\<.*?\\> [0-9]\\{,4\\} [0-9]\\{,2\\}:[0-9]\\{,2\\}"
            (let ((denote-journal-extras-title-format 'day-date-month-year-24h))
              (denote-journal-extras-daily--title-format))))))
```

You can try the test by checking if the following returns a non-nil value (a `0` still counts as non-nil):

```elisp
(and
 ;; These three should prompt, but I am here treating the
 ;; prompt as if already returned a string.  The test for
 ;; the `denote-title-prompt' can be separate.
 (stringp
  (cl-letf (((symbol-function 'denote-title-prompt) #'identity)
            (denote-journal-extras-title-format nil))
    (denote-journal-extras-daily--title-format)))

 (stringp
  (cl-letf (((symbol-function 'denote-title-prompt) #'identity)
            (denote-journal-extras-title-format t))
    (denote-journal-extras-daily--title-format)))

 (stringp
  (cl-letf (((symbol-function 'denote-title-prompt) #'identity)
            (denote-journal-extras-title-format :some-arbitrary-keyword))
    (denote-journal-extras-daily--title-format)))

 ;; And these return the following values
 (string-match-p
  "\\<.*?\\>"
  (let ((denote-journal-extras-title-format 'day))
    (denote-journal-extras-daily--title-format)))

 (string-match-p
  "\\<.*?\\> [0-9]\\{,2\\} \\<.*?\\> [0-9]\\{,4\\}"
  (let ((denote-journal-extras-title-format 'day-date-month-year))
    (denote-journal-extras-daily--title-format)))

 (string-match-p
  "\\<.*?\\> [0-9]\\{,2\\} \\<.*?\\> [0-9]\\{,4\\} [0-9]\\{,2\\}:[0-9]\\{,2\\} \\<.*?\\>"
  (let ((denote-journal-extras-title-format 'day-date-month-year-12h))
    (denote-journal-extras-daily--title-format)))

 (string-match-p
  "\\<.*?\\> [0-9]\\{,2\\} \\<.*?\\> [0-9]\\{,4\\} [0-9]\\{,2\\}:[0-9]\\{,2\\}"
  (let ((denote-journal-extras-title-format 'day-date-month-year-24h))
    (denote-journal-extras-daily--title-format))))
```

**Comment by tjstankus** [comment]
@protesilaos I updated again and it works - thank you!
